// Generated by https://quicktype.io

class EventDAO {
  String idEvent;
  dynamic idSoccerXml;
  String idApIfootball;
  String strEvent;
  String strEventAlternate;
  String strFilename;
  String strSport;
  String idLeague;
  String strLeague;
  String strSeason;
  String strDescriptionEn;
  String strHomeTeam;
  String strAwayTeam;
  String intHomeScore;
  String intRound;
  String intAwayScore;
  dynamic intSpectators;
  String strOfficial;
  String strHomeGoalDetails;
  dynamic strHomeRedCards;
  dynamic strHomeYellowCards;
  dynamic strHomeLineupGoalkeeper;
  dynamic strHomeLineupDefense;
  dynamic strHomeLineupMidfield;
  dynamic strHomeLineupForward;
  dynamic strHomeLineupSubstitutes;
  dynamic strHomeFormation;
  dynamic strAwayRedCards;
  dynamic strAwayYellowCards;
  String strAwayGoalDetails;
  dynamic strAwayLineupGoalkeeper;
  dynamic strAwayLineupDefense;
  dynamic strAwayLineupMidfield;
  dynamic strAwayLineupForward;
  dynamic strAwayLineupSubstitutes;
  dynamic strAwayFormation;
  dynamic intHomeShots;
  dynamic intAwayShots;
  String strTimestamp;
  String dateEvent;
  String dateEventLocal;
  String strTime;
  String strTimeLocal;
  dynamic strTvStation;
  String idHomeTeam;
  String idAwayTeam;
  String strResult;
  String strVenue;
  String strCountry;
  String strCity;
  dynamic strPoster;
  dynamic strSquare;
  dynamic strFanart;
  String strThumb;
  dynamic strBanner;
  dynamic strMap;
  String strTweet1;
  String strTweet2;
  String strTweet3;
  String strVideo;
  String strStatus;
  String strPostponed;
  String strLocked;

  EventDAO({
    this.idEvent,
    this.idSoccerXml,
    this.idApIfootball,
    this.strEvent,
    this.strEventAlternate,
    this.strFilename,
    this.strSport,
    this.idLeague,
    this.strLeague,
    this.strSeason,
    this.strDescriptionEn,
    this.strHomeTeam,
    this.strAwayTeam,
    this.intHomeScore,
    this.intRound,
    this.intAwayScore,
    this.intSpectators,
    this.strOfficial,
    this.strHomeGoalDetails,
    this.strHomeRedCards,
    this.strHomeYellowCards,
    this.strHomeLineupGoalkeeper,
    this.strHomeLineupDefense,
    this.strHomeLineupMidfield,
    this.strHomeLineupForward,
    this.strHomeLineupSubstitutes,
    this.strHomeFormation,
    this.strAwayRedCards,
    this.strAwayYellowCards,
    this.strAwayGoalDetails,
    this.strAwayLineupGoalkeeper,
    this.strAwayLineupDefense,
    this.strAwayLineupMidfield,
    this.strAwayLineupForward,
    this.strAwayLineupSubstitutes,
    this.strAwayFormation,
    this.intHomeShots,
    this.intAwayShots,
    this.strTimestamp,
    this.dateEvent,
    this.dateEventLocal,
    this.strTime,
    this.strTimeLocal,
    this.strTvStation,
    this.idHomeTeam,
    this.idAwayTeam,
    this.strResult,
    this.strVenue,
    this.strCountry,
    this.strCity,
    this.strPoster,
    this.strSquare,
    this.strFanart,
    this.strThumb,
    this.strBanner,
    this.strMap,
    this.strTweet1,
    this.strTweet2,
    this.strTweet3,
    this.strVideo,
    this.strStatus,
    this.strPostponed,
    this.strLocked,
  });

  factory EventDAO.fromJSON(Map<String, dynamic> map){ //Recibe json convertido a mapa
		return EventDAO(
			strEvent: map['strEvent'],
      strHomeTeam: map['strHomeTeam'],
      strAwayTeam: map['strAwayTeam'],
      intHomeScore: map['intHomeScore'],
      intAwayScore: map['intAwayScore'],
      dateEventLocal: map['dateEventLocal'],
      strTimeLocal: map['strTimeLocal'],
      strVenue: map['strVenue'],
		);
	}
}
