// Generated by https://quicktype.io

class TeamDAO {
	String idTeam;
	String idSoccerXml;
	String idApIfootball;
	String intLoved;
	String strTeam;
	String strTeamShort;
	String strAlternate;
	String intFormedYear;
	String strSport;
	String strLeague;
	String idLeague;
	String strLeague2;
	String idLeague2;
	String strLeague3;
	String idLeague3;
	String strLeague4;
	String idLeague4;
	String strLeague5;
	String idLeague5;
	String strLeague6;
	String idLeague6;
	String strLeague7;
	String idLeague7;
	String strDivision;
	String strManager;
	String strStadium;
	String strKeywords;
	String strRss;
	String strStadiumThumb;
	String strStadiumDescription;
	String strStadiumLocation;
	String intStadiumCapacity;
	String strWebsite;
	String strFacebook;
	String strTwitter;
	String strInstagram;
	String strDescriptionEn;
	String strDescriptionDe;
	String strDescriptionFr;
	String strDescriptionCn;
	String strDescriptionIt;
	String strDescriptionJp;
	String strDescriptionRu;
	String strDescriptionEs;
	String strDescriptionPt;
	String strDescriptionSe;
	String strDescriptionNl;
	String strDescriptionHu;
	String strDescriptionNo;
	String strDescriptionIl;
	String strDescriptionPl;
	String strGender;
	String strCountry;
	String strTeamBadge;
	String strTeamJersey;
	String strTeamLogo;
	String strTeamFanart1;
	String strTeamFanart2;
	String strTeamFanart3;
	String strTeamFanart4;
	String strTeamBanner;
	String strYoutube;
	String strLocked;

	TeamDAO({
		this.idTeam,
		this.idSoccerXml,
		this.idApIfootball,
		this.intLoved,
		this.strTeam,
		this.strTeamShort,
		this.strAlternate,
		this.intFormedYear,
		this.strSport,
		this.strLeague,
		this.idLeague,
		this.strLeague2,
		this.idLeague2,
		this.strLeague3,
		this.idLeague3,
		this.strLeague4,
		this.idLeague4,
		this.strLeague5,
		this.idLeague5,
		this.strLeague6,
		this.idLeague6,
		this.strLeague7,
		this.idLeague7,
		this.strDivision,
		this.strManager,
		this.strStadium,
		this.strKeywords,
		this.strRss,
		this.strStadiumThumb,
		this.strStadiumDescription,
		this.strStadiumLocation,
		this.intStadiumCapacity,
		this.strWebsite,
		this.strFacebook,
		this.strTwitter,
		this.strInstagram,
		this.strDescriptionEn,
		this.strDescriptionDe,
		this.strDescriptionFr,
		this.strDescriptionCn,
		this.strDescriptionIt,
		this.strDescriptionJp,
		this.strDescriptionRu,
		this.strDescriptionEs,
		this.strDescriptionPt,
		this.strDescriptionSe,
		this.strDescriptionNl,
		this.strDescriptionHu,
		this.strDescriptionNo,
		this.strDescriptionIl,
		this.strDescriptionPl,
		this.strGender,
		this.strCountry,
		this.strTeamBadge,
		this.strTeamJersey,
		this.strTeamLogo,
		this.strTeamFanart1,
		this.strTeamFanart2,
		this.strTeamFanart3,
		this.strTeamFanart4,
		this.strTeamBanner,
		this.strYoutube,
		this.strLocked,
	});

	factory TeamDAO.fromJSON(Map<String, dynamic> map){ //Recibe json convertido a mapa
		return TeamDAO(
			idTeam: map['idTeam'] ,
			strTeam: map['strTeam'],
			strTeamBadge: map['strTeamBadge'],
      intFormedYear: map['intFormedYear'],
      strTeamJersey: map['strTeamJersey'] ,
			strAlternate: map['strAlternate'],
			strDescriptionEn: map['strDescriptionEN'],
      strDescriptionEs: map['strDescriptionES'],
			strStadium: map['strStadium'],
			strStadiumThumb: map['strStadiumThumb'],
			strStadiumDescription: map['strStadiumDescription'],
			intStadiumCapacity: map['intStadiumCapacity'],
			strStadiumLocation: map['strStadiumLocation'] ,
			strWebsite: map['strWebsite'],
			strFacebook: map['strFacebook'],
			strTwitter: map['strTwitter'],
			strInstagram: map['strInstagram'],
		);
	}

}
